version: '3'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        DATABASE_URI: ${DATABASE_URI}
        PAYLOAD_SECRET: ${PAYLOAD_SECRET}
        S3_BUCKET_NAME: ${S3_BUCKET_NAME}
        S3_ENDPOINT: ${S3_ENDPOINT}
        S3_PUBLIC_URL: ${S3_PUBLIC_URL}
        S3_ACCESS_KEY_TOKEN: ${S3_ACCESS_KEY_TOKEN}
        S3_SECRET_KEY: ${S3_SECRET_KEY}
    ports:
      - '3000:3000'
    environment:
      - DATABASE_URI=${DATABASE_URI}
      - PAYLOAD_SECRET=${PAYLOAD_SECRET}
      - S3_BUCKET_NAME=${S3_BUCKET_NAME}
      - S3_ENDPOINT=${S3_ENDPOINT}
      - S3_PUBLIC_URL=${S3_PUBLIC_URL}
      - S3_ACCESS_KEY_TOKEN=${S3_ACCESS_KEY_TOKEN}
      - S3_SECRET_KEY=${S3_SECRET_KEY}
      - NODE_ENV=production
    env_file:
      - .env

  # Development service (use this for local dev)
  payload:
    image: node:18-alpine
    ports:
      - '3001:3000'
    volumes:
      - .:/home/node/app
      - node_modules:/home/node/app/node_modules
    working_dir: /home/node/app/
    command: sh -c "corepack enable && corepack prepare pnpm@latest --activate && pnpm install && pnpm dev"
    env_file:
      - .env

volumes:
  node_modules:
